In [1]:
import numpy as np

In [2]:
lista1 = [1,2,3,4,5,6]

In [3]:
lista1

[1, 2, 3, 4, 5, 6]

In [4]:
listaNumpy = np.array(lista1)

In [5]:
listaNumpy

array([1, 2, 3, 4, 5, 6])

In [6]:
type(lista1)

list

In [7]:
type(listaNumpy)

numpy.ndarray

In [9]:
listaNumpy * 2

array([ 2,  4,  6,  8, 10, 12])

In [10]:
listaNumpy * listaNumpy

array([ 1,  4,  9, 16, 25, 36])

In [11]:
listaNumpy**34

array([                   1,          17179869184,    16677181699666569,
                          0,  8046632842880574361, -3728758235495137280])

In [13]:
listaNumpy**123

array([                   1,                    0,  4137309267128563259,
                          0, -5141387193035002851,                    0])

In [14]:
lista2 = np.array([91,92,93,94,95,96])

In [15]:
lista2

array([91, 92, 93, 94, 95, 96])

In [16]:
lista2 + lista1

array([ 92,  94,  96,  98, 100, 102])

In [17]:
lista0 = [1,2,3]

In [19]:
lista1 + lista0

[1, 2, 3, 4, 5, 6, 1, 2, 3]

In [22]:
listaNumpy

array([1, 2, 3, 4, 5, 6])

In [25]:
listaNumpy.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
listaNumpy.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
listaNumpy.shape

(6,)

In [29]:
type(listaNumpy.shape)

tuple

In [30]:
listaNumpy*2

array([ 2,  4,  6,  8, 10, 12])

In [32]:
matriz = listaNumpy.reshape(3,2)

In [33]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
matriz*2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
matriz[2:,1:]

array([[6]])

In [43]:
matriz[1:,0:]

array([[3, 4],
       [5, 6]])

In [44]:
listaD = np.arange(0, 20, 3)

In [45]:
listaD

array([ 0,  3,  6,  9, 12, 15, 18])

In [48]:
aleatorio = np.random.randint(0,10,100)

In [49]:
aleatorio

array([4, 8, 6, 2, 1, 9, 9, 0, 9, 3, 5, 5, 1, 5, 3, 6, 3, 0, 9, 1, 9, 9,
       0, 4, 5, 9, 0, 3, 3, 5, 3, 7, 7, 4, 6, 4, 8, 5, 6, 7, 4, 2, 9, 4,
       9, 0, 0, 9, 6, 2, 6, 5, 2, 9, 8, 2, 8, 3, 7, 3, 4, 2, 7, 4, 1, 2,
       3, 6, 9, 3, 1, 8, 1, 0, 9, 3, 9, 1, 3, 4, 1, 4, 3, 9, 3, 9, 0, 8,
       6, 3, 4, 7, 2, 2, 6, 7, 3, 2, 0, 1])

In [50]:
aleatorio[1]

8

In [52]:
aleatorio[0:10]

array([4, 8, 6, 2, 1, 9, 9, 0, 9, 3])

In [53]:
type(aleatorio)

numpy.ndarray

In [54]:
aleatorio.dtype

dtype('int64')

In [55]:
aleatorio.astype(np.ubyte)

array([4, 8, 6, 2, 1, 9, 9, 0, 9, 3, 5, 5, 1, 5, 3, 6, 3, 0, 9, 1, 9, 9,
       0, 4, 5, 9, 0, 3, 3, 5, 3, 7, 7, 4, 6, 4, 8, 5, 6, 7, 4, 2, 9, 4,
       9, 0, 0, 9, 6, 2, 6, 5, 2, 9, 8, 2, 8, 3, 7, 3, 4, 2, 7, 4, 1, 2,
       3, 6, 9, 3, 1, 8, 1, 0, 9, 3, 9, 1, 3, 4, 1, 4, 3, 9, 3, 9, 0, 8,
       6, 3, 4, 7, 2, 2, 6, 7, 3, 2, 0, 1], dtype=uint8)

In [58]:
aleatorio.sort()

In [59]:
aleatorio

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [60]:
import pandas as pd

In [61]:
serie = pd.Series(aleatorio)

In [62]:
serie

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    3
29    3
     ..
70    6
71    7
72    7
73    7
74    7
75    7
76    7
77    7
78    8
79    8
80    8
81    8
82    8
83    8
84    9
85    9
86    9
87    9
88    9
89    9
90    9
91    9
92    9
93    9
94    9
95    9
96    9
97    9
98    9
99    9
Length: 100, dtype: int64